<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Sudhakar" failures="0" tests="2" name="com.aajtak.android.AppLaunch.ManTS0001" time="120.147" errors="1" timestamp="22 Aug 2022 07:48:38 GMT" skipped="1">
  <testcase classname="com.aajtak.android.AppLaunch.ManTS0001" name="Tc001" time="0.000">
    <skipped/>
  </testcase> <!-- Tc001 -->
  <testcase classname="com.aajtak.android.AppLaunch.ManTS0001" name="startServer" time="120.147">
    <error message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4725, --address, 127.0.0.1, --log, C:\Users\Sudhakar Metri\AppiumServerLogs.txt, --log-level, error, --bootstrap-port, 4728, --session-override, --default-capabilities, {\&quot;noReset\&quot;: \&quot;true\&quot;}] 
Process output: uncaughtException: EPERM: operation not permitted, stat &#039;C:\Users\Sudhakar Metri\AppiumServerLogs.txt&#039;
Error: EPERM: operation not permitted, stat &#039;C:\Users\Sudhakar Metri\AppiumServerLogs.txt&#039;
C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:307
      throw ex;
      ^

NodeError: write after end
    at writeAfterEnd (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:261:12)
    at PassThrough.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    at File.log (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\file.js:185:34)
    at File._write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:103:17)
    at doWrite (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at File.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DerivedLogger.ondata (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DerivedLogger.emit (node:events:539:35)
    at addChunk (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at DerivedLogger.Readable.push (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at DerivedLogger.Transform.push (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at DerivedLogger._transform (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)
    at DerivedLogger.Transform._read (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:164:83)
Emitted &#039;error&#039; event on PassThrough instance at:
    at errorOrDestroy (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\internal\streams\destroy.js:98:101)
    at writeAfterEnd (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:263:3)
    at PassThrough.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    [... lines matching original stack trace ...]
    at DerivedLogger.Transform._read (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)

" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4725, --address, 127.0.0.1, --log, C:\Users\Sudhakar Metri\AppiumServerLogs.txt, --log-level, error, --bootstrap-port, 4728, --session-override, --default-capabilities, {\"noReset\": \"true\"}] 
Process output: uncaughtException: EPERM: operation not permitted, stat 'C:\Users\Sudhakar Metri\AppiumServerLogs.txt'
Error: EPERM: operation not permitted, stat 'C:\Users\Sudhakar Metri\AppiumServerLogs.txt'
C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:307
      throw ex;
      ^

NodeError: write after end
    at writeAfterEnd (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:261:12)
    at PassThrough.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    at File.log (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\file.js:185:34)
    at File._write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:103:17)
    at doWrite (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at File.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DerivedLogger.ondata (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DerivedLogger.emit (node:events:539:35)
    at addChunk (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at DerivedLogger.Readable.push (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at DerivedLogger.Transform.push (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at DerivedLogger._transform (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)
    at DerivedLogger.Transform._read (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:164:83)
Emitted 'error' event on PassThrough instance at:
    at errorOrDestroy (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\internal\streams\destroy.js:98:101)
    at writeAfterEnd (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:263:3)
    at PassThrough.Writable.write (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    [... lines matching original stack trace ...]
    at DerivedLogger.Transform._read (C:\Users\Sudhakar Metri\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:146)
at com.aajtak.android.init.AppiumService.startServer(AppiumService.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4725/wd/hub/status] to be available after 120010 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:110)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:133)
... 19 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
... 21 more
]]>
    </error>
  </testcase> <!-- startServer -->
</testsuite> <!-- com.aajtak.android.AppLaunch.ManTS0001 -->
