<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TYSS-Sudhakar" name="com.aajtak.android.StoryDetails.TC_AT_StoryDetail_009" tests="1" failures="1" timestamp="12 Sep 2022 08:10:29 GMT" time="70.172" errors="0">
  <testcase name="AT_StoryDetail_009" time="70.172" classname="com.aajtak.android.StoryDetails.TC_AT_StoryDetail_009">
    <failure type="java.lang.AssertionError" message="expected [कश्मीरा के कामवाली ने पैर पकड़कर खींचे, चीखती रहीं एक्ट्रेस] but found [Kashmera Shah के कामवाली बाई ने खींचे पैर, चीखती रही एक्ट्रेस, पत्नी का बुरा हाल देख Krushna Abhishek बोले- मैंने ही पैसे दिए ]">
      <![CDATA[java.lang.AssertionError: expected [कश्मीरा के कामवाली ने पैर पकड़कर खींचे, चीखती रहीं एक्ट्रेस] but found [Kashmera Shah के कामवाली बाई ने खींचे पैर, चीखती रही एक्ट्रेस, पत्नी का बुरा हाल देख Krushna Abhishek बोले- मैंने ही पैसे दिए ]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.aajtak.android.init.Aajtak_app_Util.verifyStoryTitles(Aajtak_app_Util.java:47)
at com.aajtak.android.StoryDetails.TC_AT_StoryDetail_009.AT_StoryDetail_009(TC_AT_StoryDetail_009.java:89)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AT_StoryDetail_009 -->
</testsuite> <!-- com.aajtak.android.StoryDetails.TC_AT_StoryDetail_009 -->
